<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_submit_input_code</name>
   <tag></tag>
   <elementGuidId>d05d633e-cf11-4431-87a9-5d7910ccd18e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='coupon_apply']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#coupon_apply</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Xác nhận&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f5a132d-dbdf-47ad-90f9-8fc2cfcc7f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0546b46a-9de8-428b-80c2-68912089eab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon_apply</value>
      <webElementGuid>e937b95c-64b6-4b89-a5a4-60ab87fd6c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!border-none bg-colorMain text-4 font-semibold rounded-lg flex-[0_0_100px] md:flex-[0_0_124px] h-[45px] md:h-[48px] text-[#fff] hover:opacity-80</value>
      <webElementGuid>eb346fb2-8a90-4a89-a944-e7b103a06214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Xác nhận </value>
      <webElementGuid>e6277ac5-5c91-49bc-9018-792468168438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon_apply&quot;)</value>
      <webElementGuid>ad1a62b1-6c35-4860-aeb6-d0586e3f366c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='coupon_apply']</value>
      <webElementGuid>0f51a7c4-7a0c-4832-b6d5-811609cefea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-check']/div/div[2]/div/div/div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>283b7df8-b40d-4de1-88c1-b958b6a788bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mã giảm giá'])[1]/following::button[1]</value>
      <webElementGuid>24399da4-ab90-45c5-9555-c5d6a8502deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x 1'])[1]/following::button[1]</value>
      <webElementGuid>66e3e81e-ad90-4e09-92fe-3d9706a8e846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền'])[1]/preceding::button[1]</value>
      <webElementGuid>6aabc980-6533-492d-9545-f99d155aebdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giảm giá'])[1]/preceding::button[1]</value>
      <webElementGuid>59937267-d48d-469c-a44b-5ff7d17fbcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xác nhận']/parent::*</value>
      <webElementGuid>0f51a292-9bd5-4751-8ee3-cc0421c5f2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>ee6556f5-4ca0-4769-96e8-aa7b6bb92510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'coupon_apply' and (text() = ' Xác nhận ' or . = ' Xác nhận ')]</value>
      <webElementGuid>1dde6c2e-1e6f-4a87-b77e-1420bcd93420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
