<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_payment_bank_transfer</name>
   <tag></tag>
   <elementGuidId>fc7b50d7-00f4-4437-b302-71580e5d8700</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_bank_transfer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_bank_transfer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Chuyển khoản ngân hàng&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79dfca05-2850-41c3-b7df-3e38b162829d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ab26c16a-9e4a-4e99-a869-b4b91d5376e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_bank_transfer</value>
      <webElementGuid>952202b6-ee3d-495c-aab1-304629d1aff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>e9499d9c-79b7-49fb-9bdd-395e123ecfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-input</value>
      <webElementGuid>a8723acc-544b-44bf-a3ec-2fc53b7ce1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>bank_transfer</value>
      <webElementGuid>f9a268ad-7819-4918-9b2d-8f8ec4d910c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_bank_transfer&quot;)</value>
      <webElementGuid>5fa02d13-5398-42d4-9e89-9f5ce5a51aa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_bank_transfer']</value>
      <webElementGuid>2db91e1c-10f4-4768-83eb-6413bc8e0970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-check']/div/div/div/div/div[4]/div[2]/div[5]/label/div[2]/input</value>
      <webElementGuid>f9d914e1-fb06-427b-884d-30703d0f1077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/div[2]/input</value>
      <webElementGuid>524c39cb-bf1a-40ce-98f2-215ce73f568c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'payment_bank_transfer' and @name = 'payment_method']</value>
      <webElementGuid>c991b559-3e11-48c0-ae00-9b6cc21b2626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
