<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vat_use_address</name>
   <tag></tag>
   <elementGuidId>7b966db9-0391-4d88-8fe3-8265af51e2ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vat_use_address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vat_use_address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sử dụng địa chỉ giao hàng&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ba3120f-799a-41ca-85ed-f6e9a5a99945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>034e3a0b-b4e4-4535-84d3-6a31b71870e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vat_use_address</value>
      <webElementGuid>55832313-c316-450c-bdb0-838fa1521bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vat_use_address</value>
      <webElementGuid>d694f287-27ee-4024-a68b-7afab584776d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vat_use_address&quot;)</value>
      <webElementGuid>c932c9fa-90e8-4e36-a109-1355f095d4a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vat_use_address']</value>
      <webElementGuid>ce8dd3e1-fd74-4620-a782-d4a023ab7681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vat-payment-popup']/div[2]/div[2]/div[5]/input</value>
      <webElementGuid>13670d9d-c8de-4cdc-8cc4-92125e670661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>cab1f930-d1cd-48bf-983d-24f5affb2aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'vat_use_address' and @id = 'vat_use_address']</value>
      <webElementGuid>c2944f3d-d5b9-4b95-97b8-9358ced53012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
