<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select communes-wards</name>
   <tag></tag>
   <elementGuidId>9e2260a4-e5f6-4416-904d-3b36855abadf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='customer_ward_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer_ward_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#customer_ward_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>855999b7-6bde-4b94-af89-c6f020eaaf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_field search_address bg-[#fff]</value>
      <webElementGuid>1013bf2f-a9c5-4722-8cea-fb9b13cf2dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_ward_id</value>
      <webElementGuid>33a227dc-24e7-430e-8754-d9a653c3d881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3158677c-4285-47dc-97b8-eabda85a3fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_ward</value>
      <webElementGuid>59223881-37a0-4159-9ab8-bab5df667afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phường/Xã</value>
      <webElementGuid>52eff838-d24d-48fe-bf4b-c8f882fca35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>ward</value>
      <webElementGuid>e0159bc4-9888-4107-8ead-435386fab372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fe1aef7a-82c9-4c55-8f2e-fbe23b895c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phường/Xã</value>
      <webElementGuid>b521c902-d4df-4667-a3fc-67577469195b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_ward_id&quot;)</value>
      <webElementGuid>d2b98a6c-a12a-4e14-bd6e-5f489f2f87fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='customer_ward_id']</value>
      <webElementGuid>85ef235b-0009-4a41-8de5-da29a96b7492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-check']/div/div/div/div/div[2]/div/div[2]/div[2]/div/div/p</value>
      <webElementGuid>57431023-8f9a-466b-a739-fe8eca770f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phường/Xã'])[1]/following::p[1]</value>
      <webElementGuid>0f938a9a-0534-409c-a969-b9f11f1898df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thị Xã Sơn Tây'])[1]/following::p[1]</value>
      <webElementGuid>5c7adcab-f7e9-4073-b6c4-d76ffd0feee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phường/ Xã là bắt buộc'])[1]/preceding::p[1]</value>
      <webElementGuid>ec58bcf1-ab3f-4ac0-a941-f13948a1c930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ cụ thể'])[1]/preceding::p[1]</value>
      <webElementGuid>116ca6de-1f55-4f5a-aa6e-28a430ed6b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/p</value>
      <webElementGuid>4eb206ed-7ff8-41a0-a809-50e40776f7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'customer_ward_id' and @type = 'text' and @name = 'customer_ward' and @placeholder = 'Phường/Xã' and (text() = 'Phường/Xã' or . = 'Phường/Xã')]</value>
      <webElementGuid>2621d5fe-137c-43e6-a487-1f12e5861dce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
