<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select province-city</name>
   <tag></tag>
   <elementGuidId>c1b19e3e-3aae-40e7-87b7-0ae8c88f6ad1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='customer_province_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer_province_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tỉnh/ Thành&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5e5d304e-7cfd-4b82-a090-e4fa03437c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_field search_address !h-[45px] bg-[#fff]</value>
      <webElementGuid>762c3b52-b841-442e-b13f-eaa54c684154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_province_id</value>
      <webElementGuid>49d76f50-fc1c-4017-8803-dc9ddbd01131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>f5161bcb-6fc9-42e6-85fc-7cd8bfd2dac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d423c28d-fc48-4c4e-83d0-071473d928b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_province</value>
      <webElementGuid>5092b47d-7c2f-4e88-8c7f-c2470de91a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tỉnh/Thành phố</value>
      <webElementGuid>57a7788d-ce17-4f55-ad4d-56bcb1241284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9fc5b997-a929-4c9e-ad40-a12ac69ed4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tỉnh/ Thành </value>
      <webElementGuid>1ff1fdb4-dfde-416b-8269-57479c08cad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_province_id&quot;)</value>
      <webElementGuid>6c515596-80b3-4d51-a0f8-73e3b6cede6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='customer_province_id']</value>
      <webElementGuid>78a00380-fe1a-454f-88aa-667a26b5bf32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-check']/div/div/div/div/div[2]/div/div[2]/div/div/div/p</value>
      <webElementGuid>0dcd19fe-5e27-4f69-990c-5878af90f254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tỉnh/Thành phố'])[1]/following::p[1]</value>
      <webElementGuid>918ffe64-28fc-415b-ae90-f781d6209650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ nhận hàng'])[1]/following::p[1]</value>
      <webElementGuid>01e1b45c-7114-4547-b6a4-7cbc1aa11b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tỉnh thành là bắt buộc'])[1]/preceding::p[1]</value>
      <webElementGuid>d8bdb3b9-8753-4e8c-96cb-e2d4d841dcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hà Nội'])[1]/preceding::p[1]</value>
      <webElementGuid>6465004f-fddb-4385-bbc6-fc2dca42d183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tỉnh/ Thành']/parent::*</value>
      <webElementGuid>9758a7a0-01be-4cc2-94a5-3e7daccf9d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p</value>
      <webElementGuid>e567f40f-9b39-48cc-a75d-83fe6b76837f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'customer_province_id' and @type = 'text' and @name = 'customer_province' and @placeholder = 'Tỉnh/Thành phố' and (text() = ' Tỉnh/ Thành ' or . = ' Tỉnh/ Thành ')]</value>
      <webElementGuid>c67b5b58-20dc-42dc-9eb0-5b8040cca0c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
