<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select districts</name>
   <tag></tag>
   <elementGuidId>c6455b5c-5160-4e48-bcc8-7b90d2968634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='customer_district_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer_district_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#customer_district_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0bf6ee47-b471-4875-91f7-a141b408faed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_field search_address !h-[45px] bg-[#fff]</value>
      <webElementGuid>e3168e1b-7dd2-4a6e-8d9a-0ae617a3f6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_district_id</value>
      <webElementGuid>66c6198c-97b8-43b9-9ad7-b8945d2914b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1bb420e4-315f-4bec-a1b1-da9329dbce54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_district</value>
      <webElementGuid>859cb7dd-d2b5-4683-ac57-b7422973771b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Quận/ Huyện</value>
      <webElementGuid>2bd1edc4-4f28-483a-a130-eb6258ddb3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>99de491c-1ac1-4fb6-bf3c-dd38451ec81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1d0cfd08-fb25-4730-886c-a21a03324c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quận/ Huyện</value>
      <webElementGuid>d5889a39-97d1-4ad9-8010-2a2ca67ba173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_district_id&quot;)</value>
      <webElementGuid>c23810a0-313e-4ef6-bf7b-76857fbc5118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='customer_district_id']</value>
      <webElementGuid>896a79da-8fef-4b98-8460-a6a5bdcadb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-check']/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/p</value>
      <webElementGuid>0002a4b9-7473-4db2-8a52-51c370f12945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận/ Huyện'])[1]/following::p[1]</value>
      <webElementGuid>38577496-0555-495a-b717-720e9839553f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Điện Biên'])[1]/following::p[1]</value>
      <webElementGuid>38dd87c5-a455-443f-9a20-3d099558fb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận/ Huyện là bắt buộc'])[1]/preceding::p[1]</value>
      <webElementGuid>4a117a06-dbb0-4b2c-af7c-e9dc87a7f0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Huyện Ba Vì'])[1]/preceding::p[1]</value>
      <webElementGuid>c957d717-63c3-43ef-a2e4-51efd9f3ef33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/p</value>
      <webElementGuid>727a9760-b5c7-427a-a5dc-6c0a4202bf68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'customer_district_id' and @type = 'text' and @name = 'customer_district' and @placeholder = 'Quận/ Huyện' and (text() = 'Quận/ Huyện' or . = 'Quận/ Huyện')]</value>
      <webElementGuid>c8f857eb-bab5-438e-acd6-d5595b10db1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
