<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_quantity</name>
   <tag></tag>
   <elementGuidId>0d248340-c79c-47ec-83f7-6952ffdf56ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;quantity&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Chọn số lượng&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f3e9876-54ee-4065-8fbc-9565fb4051ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92b37feb-2ed3-4250-ab93-d5d51bbb6a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Chọn số lượng</value>
      <webElementGuid>bf552223-8676-4dca-bb86-9716f1b8f68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-quantity__input flex-[0_0_calc(100%_-_72px)] h-[36px] text-center border-0 border-solid border-l-[1px] border-r-[1px] border-[#E3E2E6] focus:outline-none</value>
      <webElementGuid>793209b6-d5bf-465d-bd33-1ab2a35b4aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>cbb2479f-4536-46e1-80f9-248bbb9349a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f80fa703-fae4-4910-9afd-4dbe409153cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>87ea5030-0365-4585-bf99-41890965f0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b9972156-dee1-4f33-a123-ee94e2b20005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>af598924-149f-4a18-9f46-47f8b2d0c532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>14c7ce32-21f3-4fb2-a468-ab6f31840386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>76856262-6494-4443-8cc9-8dde817acb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-outstock</name>
      <type>Main</type>
      <value>Kho hàng còn 100 sản phẩm</value>
      <webElementGuid>919f63e5-9075-4ee3-937b-24d2df93472d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;pt-8&quot;]/div[@class=&quot;product-single&quot;]/section[@class=&quot;product-single__wrap mb-[24px]&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex gap-9 flex-wrap p-[32px] bg-[#F6F7F8] rounded-[8px]&quot;]/div[@class=&quot;xl:w-[calc(100%-36px-700px)] lg:w-1/3 w-full flex flex-col gap-0&quot;]/div[@class=&quot;top-information__wrap cart&quot;]/div[@class=&quot;flex flex-wrap gap-2 items-center&quot;]/div[@class=&quot;flex flex-wrap border border-solid border-[#E3E2E6] rounded flex-[0_0_140px] overflow-hidden h-full&quot;]/input[@class=&quot;cart-quantity__input flex-[0_0_calc(100%_-_72px)] h-[36px] text-center border-0 border-solid border-l-[1px] border-r-[1px] border-[#E3E2E6] focus:outline-none&quot;]</value>
      <webElementGuid>ae4acae3-67de-4ddf-bfca-724d2814fe2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='quantity']</value>
      <webElementGuid>6b5e5585-b54b-43ca-a18c-714a7037f42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/main/div/div[2]/section/div/div/div/div[2]/div/div[7]/div[2]/input</value>
      <webElementGuid>10287472-e2da-451a-b32f-3d298263f9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>62d61a63-6dce-4d53-a8e5-243440935036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'quantity']</value>
      <webElementGuid>bb17ecee-cd3d-46be-b898-f7fe8d0d929c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
