<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_cart-item 3</name>
   <tag></tag>
   <elementGuidId>bcd2518f-5206-43be-b773-1c1577c1e336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cart-item-3cd322c0ae2639a8003feab6a57dfca2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cart-item-3cd322c0ae2639a8003feab6a57dfca2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df701ff9-4836-4503-ba23-c01473eaf857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>315d4447-210d-448c-a7a4-b2e4aebe20d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input w-[18px] h-[18px] accent-colorMain</value>
      <webElementGuid>b4b642be-b9a8-4cf6-b840-c5c0951fcc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>one</value>
      <webElementGuid>c49c5f3a-dc4e-4a15-b04a-27389f4fed01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-item-3cd322c0ae2639a8003feab6a57dfca2</value>
      <webElementGuid>723339c2-2cb6-491b-a852-6beaa303575e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected-id</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>38b8e0c3-46b0-4dc6-b641-12b5d288480a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-item-3cd322c0ae2639a8003feab6a57dfca2&quot;)</value>
      <webElementGuid>d6fc6da9-e986-4367-9173-991600e36591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cart-item-3cd322c0ae2639a8003feab6a57dfca2']</value>
      <webElementGuid>5886ff8b-77fd-419c-86e1-1ef4c7009864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-page__content']/div/div/div[3]/div[3]/div/div/div/input</value>
      <webElementGuid>2070c652-15f9-4921-a7f6-f9db2d913557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>9db13923-52f2-4c55-b816-7e3e6e995f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cart-item-3cd322c0ae2639a8003feab6a57dfca2']</value>
      <webElementGuid>fc372d89-a416-4b56-8fd0-44276673b08b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
