<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_cart-item 2</name>
   <tag></tag>
   <elementGuidId>0c9e1d8d-ae33-496f-9ace-5a3743c9391e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cart-item-06a4cff5ed570d53ce76aa04966ebbd4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cart-item-06a4cff5ed570d53ce76aa04966ebbd4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0fc4084-d2b5-4b42-8499-e200d03ce6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a439a69a-01f5-4c7e-bb60-d22958579c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input w-[18px] h-[18px] accent-colorMain</value>
      <webElementGuid>38b9e795-d0ea-4995-afb8-1c1e2d2d8847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>one</value>
      <webElementGuid>796bb335-53d4-4b08-bef6-8398716b40ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-item-06a4cff5ed570d53ce76aa04966ebbd4</value>
      <webElementGuid>b5936707-6b35-4805-ae86-ec3706381a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected-id</name>
      <type>Main</type>
      <value>73</value>
      <webElementGuid>113f38a3-5d4c-4e4c-9658-49fed1e48fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-item-06a4cff5ed570d53ce76aa04966ebbd4&quot;)</value>
      <webElementGuid>25eb1f15-72b3-479b-b428-c9d166dd661f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cart-item-06a4cff5ed570d53ce76aa04966ebbd4']</value>
      <webElementGuid>269fa7ed-68bb-44b1-917c-9a826ea5c979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-page__content']/div/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>4b2b43e5-5a08-4e03-9e35-bd4d4e95e612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>f124516d-bcc3-4269-a246-f2779b54058f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cart-item-06a4cff5ed570d53ce76aa04966ebbd4']</value>
      <webElementGuid>02b4edbe-5dda-4ea4-bd0a-ec6d74e2d319</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
