<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_cart-item 1</name>
   <tag></tag>
   <elementGuidId>ebabb121-f2dc-46cd-bde8-4d198b53b47f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cart-item-d7bfb50013a02113c86b34f48bb952a1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cart-item-d7bfb50013a02113c86b34f48bb952a1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae66506e-90a0-4911-9f41-6d49214162ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>50b1b1c8-764d-4530-bda0-1d8eb3f9626d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input w-[18px] h-[18px] accent-colorMain</value>
      <webElementGuid>4acdbf91-3a1d-4198-afec-8689eaafd934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>one</value>
      <webElementGuid>c32152f7-c20a-47ca-916e-cefd8fa82bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-item-d7bfb50013a02113c86b34f48bb952a1</value>
      <webElementGuid>1bd30b2e-b682-4aa6-9b4c-b1703d1273b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected-id</name>
      <type>Main</type>
      <value>74</value>
      <webElementGuid>8e09b742-91fb-4b5d-ac07-0a02f03e3fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-item-d7bfb50013a02113c86b34f48bb952a1&quot;)</value>
      <webElementGuid>16484b41-b632-4b8e-958b-319a6386ab5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cart-item-d7bfb50013a02113c86b34f48bb952a1']</value>
      <webElementGuid>fa771618-18d2-4c5e-b848-4b6f523bc66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-page__content']/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>37c29e34-f986-4e3d-9d46-d421e6932fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>4fec150c-2856-486f-8428-67ab6e53e0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cart-item-d7bfb50013a02113c86b34f48bb952a1']</value>
      <webElementGuid>ed16e31d-fea6-425c-8ad7-78f2a5c38a35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
