<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_quantity_ giohang</name>
   <tag></tag>
   <elementGuidId>b1662bfc-05a6-46ab-ba32-6c7751e585eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='quantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;quantity&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2408888d-f441-4a6d-88f3-40bed344be5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>727d632a-b908-497f-a886-a160ff87516f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-quantity__input flex-[0_0_calc(100%_-_72px)] text-center border-0 border-solid border-l-[1px] border-r-[1px] border-[#E3E2E6] focus:outline-none</value>
      <webElementGuid>cf328c5a-c4c6-4435-a07a-af9a9c93368a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>a0aa7506-60ef-4ede-b848-8253c8cb7b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8a868e95-dffb-4d25-afe2-a26983bf251f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e82883ff-26ff-41de-8ac8-09d9ce39b663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>86eda756-55fd-4536-9bf4-b3369d3455f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>13640778-b171-4a90-b99f-d92ae887c6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2eccde49-6924-4c60-8b74-66d701746400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7f7afd0e-749a-405c-929a-7981a0788c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>d7bfb50013a02113c86b34f48bb952a1</value>
      <webElementGuid>14419671-8b6f-4dab-be58-1ea4121580e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-outstock</name>
      <type>Main</type>
      <value>Kho hàng còn 64 sản phẩm</value>
      <webElementGuid>09e3bddf-2159-4fb8-a4ab-d6be8b0cd0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>change</value>
      <webElementGuid>093d0803-08f2-4895-86d1-e80d7368b28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-page__content&quot;)/div[@class=&quot;w-full block xl:px-[72px] md:px-4 px-0 cart-sidebar__wrapper checkout-page__cart&quot;]/div[@class=&quot;cart-wrap w-full p-4 md:p-8 border-checkout-cart rounded-lg rounded-[8px] bg-[#F3F3F3]&quot;]/div[@class=&quot;checkout-page__cart--cart-list&quot;]/div[@class=&quot;py-6 border-b border-[#C3C6CF] last:border-b-0 relative&quot;]/div[@class=&quot;flex items-start justify-between cart-item gap-4&quot;]/div[@class=&quot;flex md:flex-row flex-col md:items-center items-start justify-between gap-4 md:w-[calc(100%-92px)] w-[calc(100%-40px)]&quot;]/div[@class=&quot;md:w-[calc(100%-134px)] w-full&quot;]/div[2]/div[@class=&quot;cart flex justify-start items-center gap-2 !my-0&quot;]/div[@class=&quot;cart-quantity flex flex-wrap border border-solid border-[#E3E2E6] rounded flex-[0_0_140px] overflow-hidden h-full&quot;]/input[@class=&quot;cart-quantity__input flex-[0_0_calc(100%_-_72px)] text-center border-0 border-solid border-l-[1px] border-r-[1px] border-[#E3E2E6] focus:outline-none&quot;]</value>
      <webElementGuid>257d06a9-2d02-40ed-b1bd-17cd89e8d324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='quantity']</value>
      <webElementGuid>8f93a5f8-4574-4fa3-bc83-96a174e28531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-page__content']/div/div/div[3]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>d33ae9dc-adad-4b97-a23e-5ea7c20c8365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>9240ab58-2f21-4cd4-9b7d-28785133195a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'quantity']</value>
      <webElementGuid>d322ff18-6e85-4c56-abba-8207da286da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
