<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next</name>
   <tag></tag>
   <elementGuidId>113368f3-0895-4df2-acea-f5eb213c60b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='redirect-to-payment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#redirect-to-payment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tiếp theo&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ac271f6-6100-416a-bb7e-019d57bd33b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://maxe.chanh.in/checkout</value>
      <webElementGuid>b04b06e9-756d-4324-a4e7-f4283cead19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-[20px] h-12 flex items-center justify-center bg-colorMain rounded-full hover:opacity-80</value>
      <webElementGuid>a658b408-040a-45d7-a659-d77ab2efb9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tiếp theo</value>
      <webElementGuid>969b976f-7894-4cf9-90c9-211851a26725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redirect-to-payment</value>
      <webElementGuid>25eb6fd7-aa00-431c-97c6-3b6abba36a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text-null</name>
      <type>Main</type>
      <value>Chọn sản phẩm để mua hàng</value>
      <webElementGuid>21a8863a-30d2-4494-8ed7-698278f21954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Tiếp theo       </value>
      <webElementGuid>d512a43d-7128-42de-9dfb-d9d8f32de9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redirect-to-payment&quot;)</value>
      <webElementGuid>19de7d95-1af7-4810-8d4e-d9c75b2f3d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='redirect-to-payment']</value>
      <webElementGuid>b5be97e0-f219-41ad-9cde-55e45a10e60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/main/div[2]/div[2]/div/div[2]/a</value>
      <webElementGuid>58b76ae4-4e7f-48ad-8ee8-740b332c995e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loa âm thanh 1'])[1]/following::a[1]</value>
      <webElementGuid>c963c7b8-aefb-413e-ba1c-021102d1e23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://maxe.chanh.in/checkout')]</value>
      <webElementGuid>4de298b4-e43c-40b4-9842-b0faa1728514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>0a2ad5eb-8f4b-4f8a-806e-b9cc47be60bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://maxe.chanh.in/checkout' and @id = 'redirect-to-payment' and (text() = '  Tiếp theo       ' or . = '  Tiếp theo       ')]</value>
      <webElementGuid>894af6b4-8496-4e5f-8073-66df39311ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
